---
title: The guideline name
subtitle: Technical Guideline Series
date: today
author:
  - name: AAA BBB
    id: sb
    orcid: 1234-1234-1234-1234
    email: jaaa@bbb.cc
    affiliation: 
      - name: Whatever Institute
        city: Providence
        state: RI
        url: www.brown.edu
    roles: [author, editor]
  - name: CCC DDD
    id: cd
    orcid: 2345-2345-2345-2345
    email: bbb@ccc.dd
    affiliation: 
      - name: Another Great Institute
        city: Providence
        state: RI
        url: www.brown.edu
abstract: > 
  The short abstract goes here 
  and can go over multiple lines. ...
# keywords:
#   - aaaaa
#   - bbbbb
license: "CC BY"
copyright: 
  holder: No idea
  year: 2023
citation: 
  type: report
  container-title: IPBES Technical Guidelines Series
  doi: 10.5281/zenodo.10037104
doi: 10.5281/zenodo.10037104
version: 0.0.1

format:
    html:
        toc: true
        toc-depth: 4
        toc_expand: true
        embed-resources: true
        code-fold: true
        code-summary: 'Show the code'
        keep-md: true
---

```{r}
#| label: setup
#| include: false
# This is needed to execute the inline code
```

%Please fill in the headers accordingly.%
%INCREASE THE VERSION BEFORE A NEW RELEASE.%
% All parts which need to be changed are marked with a `%` sign.%

**Reviewed by**:

- [%Aidin Niamir%](mailto:xxx@yyy.zz)
- [%Yanina V. Sica%](mailto:xxx@yyy.zz) - IPBES Technical Support Unit for Knowledge and Data
- ...

*For any inquires please contact [aidin.niamir\@senckenberg.de](mailto:aidin.niamir@senckenberg.de)* 



## Workflow for TG Development (Here goes the TG)
**Version:** `r rmarkdown::metadata$version`

1. Update all metadata and the version number in the `README.md` YAML headers of this file
2. Add abstract to both documents
4. Link the github repo to Zenodo so that each release is automatically added to Zenodo
3. Write the TG in this document

## Workflow for TG Publication

Publication is done by creaating a new release, which is automatically pushed to zenodo as the repository
is linked to Zenodo.
There are a few manual steps which need to be done:

1. Update the version number in the `YAML headers of this file
2. render this document to HTML (at the moment, the only supported format - but we can think about offering pdf versions for the offline reading)
3. Check the renderd html document and make sure that all links are working and that the document is rendered correctly
4. Do a final check of the README.md to make sure that it is still up to date
5. Make sure that the version in the document and the tag for the release corresponds (i.e. tag should be vX.Y.Z)
6. Create a new release on github and upload the rendered html document as a release asset

# Workflow for review

1. Export the TG as a docx file
2. upload the docx file to google drive (convert it if you want to to google doc format - it makes it faster to wotk with the document but it not necessary)
3. get the link to the TG on google drive (**The share sould be `Comment only`!**) and add it to this TG file [To review, click here](LINK.TO.GOOGLE.DOC)
4. export the TG to pdf, which now contains the link to the google doc
5. send the pdf to the reviewers with the information that for reviewing, they should open the document on google docs using the link in the document (and in the email)
6. at ther end, transfer the requested changes from the google doc to the TG and update the html on github
